name: PR Build Check

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af #v4.1.0
        with:
          node-version: "22.10.0"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Check manifest version
        run: |
          VERSION=$(node -p "require('./manifest.json').version")
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Manifest version is valid: $VERSION"
          else
            echo "Invalid manifest version: $VERSION"
            exit 1
          fi

      - name: Validate manifest permissions
        run: |
          PERMISSIONS=$(node -p "JSON.stringify(require('./manifest.json').permissions)")
          EXPECTED_PERMISSIONS='["activeTab","scripting","storage","downloads","proxy","webRequest"]'
          if [ "$PERMISSIONS" = "$EXPECTED_PERMISSIONS" ]; then
            echo "Manifest permissions are valid"
          else
            echo "Unexpected manifest permissions: $PERMISSIONS"
            exit 1
          fi

      - name: Check Vite config
        run: |
          if grep -q "svelte({" vite.config.ts && grep -q "build: {" vite.config.ts; then
            echo "Vite config seems to be properly set up"
          else
            echo "Vite config might be missing important configurations"
            exit 1
          fi
