repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=36000]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace

  # Github actions
  - repo: https://github.com/rhysd/actionlint
    rev: 5db9d9cde2f3deb5035dea3e45f0a9fff2f29448
    hooks:
      - id: actionlint
        name: Check Github Actions

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458
    hooks:
      - id: detect-secrets

  # TypeScript/JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 82ec55bf6a15fa259e1115b3a89adb99cb8827b2
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        types: [file]
        additional_dependencies:
          - eslint
          - typescript
          - eslint-plugin-svelte
          - svelte
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"

  # Prettier formatting for TypeScript and Svelte
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea
    hooks:
      - id: prettier
        types_or: [javascript, typescript, svelte]
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte

  # TypeScript type checking
  - repo: local
    hooks:
      - id: tsc
        name: TypeScript type checking
        entry: npx tsc
        language: node
        pass_filenames: false
        types_or: [typescript, svelte]
        additional_dependencies: ["typescript"]

  # Svelte check
  - repo: local
    hooks:
      - id: svelte-check
        name: Svelte type checking
        entry: npx svelte-check
        language: node
        pass_filenames: false
        types: [svelte]
        additional_dependencies: ["svelte-check"]

  - repo: local
    hooks:
      # Ensure GH actions are pinned to a specific hash
      - id: check-github-actions
        name: Check GitHub Actions for Pinned Dependencies
        entry: python .scripts/check_pinned_hash_dependencies.py
        language: python
        files: \.github/.*\.yml$
